server:
  address: 0.0.0.0:8080
  environment: development
  serverUrl: http://192.168.1.126:8080
  secretKey: CHANGEME
  formbeeKey: APIKEY
oauth:
  google:
    secretsFile: 'TODO'
    appId: 'TODO'
    redirectUri: 'TODO'
database:
  driver: sqlite
  uri: ./scratch/test.db
  # uri: file::memory:?cache=shared
nats:
  inProcess: true
  url: "127.0.0.1:4222"
imagor:
  url: http://localhost:8000