services:
  nats:
    image: nats
    container_name: nats
    ports:
      - 4222:4222
  cache:
    image: memcached
    container_name: cache
    ports:
      - 11211:11211
    command:
      - memcached
      - --memory-limit=500m
      - -I 100m
  imagorvideo:
    image: shumc/imagorvideo
    command: -imagor-unsafe
    container_name: imagorvideo
    restart: unless-stopped
    # as in dev mode need to query the local running service
    network_mode: host