services:
  nats:
    image: nats
    container_name: nats
    ports:
      - 4222:4222
  imagorvideo:
    image: shumc/imagorvideo
    command: -imagor-unsafe
    container_name: imagorvideo
    restart: unless-stopped
    # as in dev mode need to query the local running service
    network_mode: host