filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
with-expecter: True
packages:
  github.com/jj-style/eventpix/backend/internal/pkg/thumber:
    interfaces:
      Thumber:
  github.com/jj-style/eventpix/backend/internal/data/db:
    interfaces:
      DB:
  github.com/jj-style/eventpix/backend/internal/data/storage:
    interfaces:
      Storage: