server:
  address: localhost:8080
  environment: development
database:
  driver: sqlite
  uri: test.db
  # uri: file::memory:?cache=shared
pubsub:
  mode: memory
  # mode: nats
  inProcess: false
  nats:
    url: "127.0.0.1:4222"
  workers: 2