__git_version := `git rev-parse --short HEAD`
__module := 'github.com/jj-style/eventpix'
__cmd_module := __module / 'backend' / 'cmd'

[private]
help:
    just --list --unsorted

# generate code
generate:
    go generate ./...

build version=__git_version:
    @mkdir -p bin
    go build -ldflags="-X '{{__cmd_module}}.Version={{version}}'" -o bin/eventpix main.go 