// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/ThreeDotsLabs/watermill/message"
	"github.com/jj-style/eventpix/backend/internal/config"
	"github.com/jj-style/eventpix/backend/internal/data/db"
	"github.com/jj-style/eventpix/backend/internal/pkg/pubsub"
	"github.com/jj-style/eventpix/backend/internal/pkg/thumber"
	"github.com/jj-style/eventpix/backend/internal/server"
	"github.com/jj-style/eventpix/backend/internal/service"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeServer(cfg2 *config.Config, logger *zap.Logger) (*serverApp, func(), error) {
	database := config.DatabaseProvider(cfg2)
	dbDB, cleanup, err := db.NewDb(database, logger)
	if err != nil {
		return nil, nil, err
	}
	pubSub := config.PubSubProvider(cfg2)
	publisher, cleanup2, err := pubsub.NewPublisher(pubSub)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pictureServiceHandler := service.NewPictureServiceServer(logger, dbDB, publisher)
	httpServer := server.NewServer(cfg2, pictureServiceHandler, logger)
	cmdServerApp, cleanup3, err := newServerApp(cfg2, logger, httpServer, publisher)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return cmdServerApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func initializeThumbnailer(cfg2 *config.Config, logger *zap.Logger) (*service.Thumbnailer, func(), error) {
	database := config.DatabaseProvider(cfg2)
	dbDB, cleanup, err := db.NewDb(database, logger)
	if err != nil {
		return nil, nil, err
	}
	thumberThumber := thumber.NewThumber()
	pubSub := config.PubSubProvider(cfg2)
	subscriber, cleanup2, err := pubsub.NewSubscriber(pubSub)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	thumbnailer, err := service.NewThumbnailer(dbDB, thumberThumber, subscriber, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return thumbnailer, func() {
		cleanup2()
		cleanup()
	}, nil
}

func initializeMemThumbnailer(cfg2 *config.Config, logger *zap.Logger, subscriber message.Subscriber) (*service.Thumbnailer, func(), error) {
	database := config.DatabaseProvider(cfg2)
	dbDB, cleanup, err := db.NewDb(database, logger)
	if err != nil {
		return nil, nil, err
	}
	thumberThumber := thumber.NewThumber()
	thumbnailer, err := service.NewThumbnailer(dbDB, thumberThumber, subscriber, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return thumbnailer, func() {
		cleanup()
	}, nil
}
