// Code generated by mockery v2.47.0. DO NOT EDIT.

package db

import (
	context "context"

	db "github.com/jj-style/eventpix/backend/internal/data/db"
	mock "github.com/stretchr/testify/mock"
)

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// AddFileInfo provides a mock function with given fields: _a0, _a1
func (_m *MockDB) AddFileInfo(_a0 context.Context, _a1 *db.FileInfo) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddFileInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.FileInfo) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDB_AddFileInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFileInfo'
type MockDB_AddFileInfo_Call struct {
	*mock.Call
}

// AddFileInfo is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *db.FileInfo
func (_e *MockDB_Expecter) AddFileInfo(_a0 interface{}, _a1 interface{}) *MockDB_AddFileInfo_Call {
	return &MockDB_AddFileInfo_Call{Call: _e.mock.On("AddFileInfo", _a0, _a1)}
}

func (_c *MockDB_AddFileInfo_Call) Run(run func(_a0 context.Context, _a1 *db.FileInfo)) *MockDB_AddFileInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.FileInfo))
	})
	return _c
}

func (_c *MockDB_AddFileInfo_Call) Return(_a0 error) *MockDB_AddFileInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_AddFileInfo_Call) RunAndReturn(run func(context.Context, *db.FileInfo) error) *MockDB_AddFileInfo_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function with given fields: _a0, _a1
func (_m *MockDB) CreateEvent(_a0 context.Context, _a1 *db.Event) (uint, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.Event) (uint, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.Event) uint); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.Event) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockDB_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *db.Event
func (_e *MockDB_Expecter) CreateEvent(_a0 interface{}, _a1 interface{}) *MockDB_CreateEvent_Call {
	return &MockDB_CreateEvent_Call{Call: _e.mock.On("CreateEvent", _a0, _a1)}
}

func (_c *MockDB_CreateEvent_Call) Run(run func(_a0 context.Context, _a1 *db.Event)) *MockDB_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*db.Event))
	})
	return _c
}

func (_c *MockDB_CreateEvent_Call) Return(_a0 uint, _a1 error) *MockDB_CreateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_CreateEvent_Call) RunAndReturn(run func(context.Context, *db.Event) (uint, error)) *MockDB_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function with given fields: _a0, _a1
func (_m *MockDB) GetEvent(_a0 context.Context, _a1 uint64) (*db.Event, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *db.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*db.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *db.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockDB_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uint64
func (_e *MockDB_Expecter) GetEvent(_a0 interface{}, _a1 interface{}) *MockDB_GetEvent_Call {
	return &MockDB_GetEvent_Call{Call: _e.mock.On("GetEvent", _a0, _a1)}
}

func (_c *MockDB_GetEvent_Call) Run(run func(_a0 context.Context, _a1 uint64)) *MockDB_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockDB_GetEvent_Call) Return(_a0 *db.Event, _a1 error) *MockDB_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_GetEvent_Call) RunAndReturn(run func(context.Context, uint64) (*db.Event, error)) *MockDB_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: _a0
func (_m *MockDB) GetEvents(_a0 context.Context) ([]*db.Event, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []*db.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*db.Event, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*db.Event); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDB_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockDB_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDB_Expecter) GetEvents(_a0 interface{}) *MockDB_GetEvents_Call {
	return &MockDB_GetEvents_Call{Call: _e.mock.On("GetEvents", _a0)}
}

func (_c *MockDB_GetEvents_Call) Run(run func(_a0 context.Context)) *MockDB_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDB_GetEvents_Call) Return(_a0 []*db.Event, _a1 error) *MockDB_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDB_GetEvents_Call) RunAndReturn(run func(context.Context) ([]*db.Event, error)) *MockDB_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
