name: Build docker
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: jj-style
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest
          install: true
          network: host
          buildkitd-config-inline: |
            [registry."git.home.jjstyle.dev"]
              ca=["/etc/ssl/certs/ca-certificates.crt"]   

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.home.jjstyle.dev
          username: ${{ env.DOCKER_ORG }}
          password: ${{ secrets.CI_PACKAGE_WRITE }}

      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(git describe --tags --always | sed 's/^v//') >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: |
            linux/amd64
          tags: |
            git.home.jjstyle.dev/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
            git.home.jjstyle.dev/${{ env.DOCKER_ORG }}/${{ steps.meta.outputs.REPO_NAME }}:latest 