name: Build docker
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: # replace it with your local IP
          config-inline: |
            [registry."gitea:3000"] 
              http = true
              insecure = true

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: gitea:3000
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PACKAGE_WRITE }}

      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: |
            linux/amd64
            linux/arm64  
          tags: gitea:3000/${{ github.actor }}/${{ gitea.repository }}:latest