// Code generated by gonstructor --type=StorageService --constructorTypes=allArgs; DO NOT EDIT.

package service

import (
	"github.com/jj-style/eventpix/backend/internal/data/db"
	"go.uber.org/zap"
)

func NewStorageService(
	db db.DB,
	log *zap.Logger,
) *StorageService {
	return &StorageService{
		db:  db,
		log: log,
	}
}
