// Code generated by mockery v2.42.0. DO NOT EDIT.

package thumber

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockThumber is an autogenerated mock type for the Thumber type
type MockThumber struct {
	mock.Mock
}

type MockThumber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThumber) EXPECT() *MockThumber_Expecter {
	return &MockThumber_Expecter{mock: &_m.Mock}
}

// Thumb provides a mock function with given fields: _a0
func (_m *MockThumber) Thumb(_a0 io.Reader) (io.Reader, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Thumb")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Reader) (io.Reader, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) io.Reader); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockThumber_Thumb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Thumb'
type MockThumber_Thumb_Call struct {
	*mock.Call
}

// Thumb is a helper method to define mock.On call
//   - _a0 io.Reader
func (_e *MockThumber_Expecter) Thumb(_a0 interface{}) *MockThumber_Thumb_Call {
	return &MockThumber_Thumb_Call{Call: _e.mock.On("Thumb", _a0)}
}

func (_c *MockThumber_Thumb_Call) Run(run func(_a0 io.Reader)) *MockThumber_Thumb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *MockThumber_Thumb_Call) Return(_a0 io.Reader, _a1 error) *MockThumber_Thumb_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockThumber_Thumb_Call) RunAndReturn(run func(io.Reader) (io.Reader, error)) *MockThumber_Thumb_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThumber creates a new instance of MockThumber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThumber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThumber {
	mock := &MockThumber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
